version: "2"
checks:
  method-lines:
    config:
      threshold: 30
  method-complexity:
    config:
      threshold: 7
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
